name: Run the test suite
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        env:
          FREEMOBILE_ACCOUNT: ${{secrets.FREEMOBILE_ACCOUNT}}
          FREEMOBILE_API_KEY: ${{secrets.FREEMOBILE_API_KEY}}
